// Generates `dist/tokens.css` from the compiled design tokens (`dist/index.js`).
// Runs after `tsc` in the package `build` script. Emits:
//   - `:root` custom properties (colors, shadows, motion, spacing, radii, type, semantic)
//   - a Tailwind v4 `@theme inline { … }` block mapping the brand palette + shadows
//     + spacing to utilities, reproducing the apps' previous hand-copied blocks so
//     rendering is unchanged.
//
// IMPORTANT (no-visual-change gate): radii are emitted as `:root` vars only — they
// are NOT mapped into `@theme` because that would override Tailwind's built-in
// `rounded-*` scale already used across the apps. Promote them to utilities in a
// later, intentional restyle phase.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import {
  colors,
  spacing,
  radii,
  typeScale,
  shadows,
  durations,
  easings,
  fonts,
  semantic,
} from "../dist/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, "..", "dist", "tokens.css");

const camelToKebab = (key) =>
  key.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

const lines = [];
const push = (line = "") => lines.push(line);

push("/* AUTO-GENERATED by scripts/build-tokens.mjs from theme.ts. Do not edit. */");
push("");
push(":root {");

// Colors (raw palette) → --<kebab>
push("  /* palette */");
for (const [key, value] of Object.entries(colors)) {
  push(`  --${camelToKebab(key)}: ${value};`);
}

// Shadows → --shadow-<key>
push("");
push("  /* shadows */");
for (const [key, value] of Object.entries(shadows)) {
  push(`  --shadow-${camelToKebab(key)}: ${value};`);
}

// Motion → --duration-* / --ease-*
push("");
push("  /* motion */");
for (const [key, value] of Object.entries(durations)) {
  push(`  --duration-${key}: ${value}ms;`);
}
for (const [key, value] of Object.entries(easings)) {
  push(`  --ease-${camelToKebab(key)}: ${value};`);
}

// Spacing → --space-*
push("");
push("  /* spacing */");
for (const [key, value] of Object.entries(spacing)) {
  push(`  --space-${key}: ${value}px;`);
}

// Radii → --radius-* (root vars only; intentionally not Tailwind utilities)
push("");
push("  /* radii */");
for (const [key, value] of Object.entries(radii)) {
  const unit = typeof value === "number" && value < 1000 ? `${value}px` : `${value}px`;
  push(`  --radius-${key}: ${unit};`);
}

// Type scale → --text-<key>-size / --text-<key>-line / --text-<key>-tracking
push("");
push("  /* type scale */");
for (const [key, step] of Object.entries(typeScale)) {
  push(`  --text-${key}-size: ${step.fontSize}px;`);
  push(`  --text-${key}-line: ${step.lineHeight}px;`);
  if (typeof step.letterSpacing === "number") {
    push(`  --text-${key}-tracking: ${step.letterSpacing}px;`);
  }
  if (typeof step.fontWeight === "number") {
    push(`  --text-${key}-weight: ${step.fontWeight};`);
  }
}

// Font family vars (the next/font CSS vars are supplied by each app's layout)
push("");
push("  /* fonts */");
push(`  --font-sans: var(${fonts.webSansVar}), ${fonts.webSansStack};`);
push(`  --font-display: var(${fonts.webDisplayVar}), ${fonts.webDisplayStack};`);

// Semantic role layer → --<group>-<role>
push("");
push("  /* semantic roles (dark) */");
for (const [group, roles] of Object.entries(semantic)) {
  for (const [role, value] of Object.entries(roles)) {
    push(`  --${camelToKebab(group)}-${camelToKebab(role)}: ${value};`);
  }
}

push("}");
push("");

// ── Tailwind v4 utilities ────────────────────────────────────────────────────
push("@theme inline {");
push("  /* brand palette utilities (bg, text, border) */");
for (const key of Object.keys(colors)) {
  const kebab = camelToKebab(key);
  push(`  --color-${kebab}: var(--${kebab});`);
}
push("");
push("  /* shadow utilities */");
for (const key of Object.keys(shadows)) {
  const kebab = camelToKebab(key);
  push(`  --shadow-${kebab}: var(--shadow-${kebab});`);
}
push("");
push("  /* fonts → font-sans / font-display */");
push("  --font-sans: var(--font-sans);");
push("  --font-display: var(--font-display);");
push("}");
push("");

writeFileSync(outFile, lines.join("\n"), "utf8");
console.log(`build-tokens: wrote ${outFile}`);
